exports.records = function() {
	return [
	{ "name" : "52nd Street - Cool As Ice 1983" },
	{ "name" : "52nd Street - Tell Me (How It Feels) (12&quot;) 1986" },
	{ "name" : "80 s Ladies - Turned On To You 1981" },
	{ "name" : "Adele Bertei - Build Me A Bridge 1983" },
	{ "name" : "Adiche - Get Ready (12&quot;) 1985" },
	{ "name" : "Advance - Take Me To The Top 1983" },
	{ "name" : "Affinity - Don't Go Away 1983" },
	{ "name" : "Al Hudson - If You Feel Like Dancing 1977" },
	{ "name" : "Aleem - Confusion (12&quot;) 1985" },
	{ "name" : "Aleem - Love's On Fire (12&quot;) 1986" },
	{ "name" : "Aleem - Release Yourself 1984" },
	{ "name" : "Alexander Robotnick - Problemes D'Amour (12&quot;) 1985" },
	{ "name" : "Alfie - Star (12&quot;) 1985" },
	{ "name" : "Alfie Silas - A Puppet To You (LP or 12&quot;) 1982" },
	{ "name" : "Alfie Silas - Communicate (LP Cut) 1982" },
	{ "name" : "Alfredo De La Fe - Hot To Trot 1977 Alfredo De La Fe" },
	{ "name" : "Alicia Myers - I Want To Thank You (LP) 1982" },
	{ "name" : "Alma Faye - Don't Fall In Love 1979" },
	{ "name" : "Alma Faye - It's Over (12&quot; ext. mix) 1979" },
	{ "name" : "Alma Faye - Stop, I Don't Need No Sympathy 1977" },
	{ "name" : "AM-FM - You Are The One 1982" },
	{ "name" : "Amii Stewart - I'm Gonna Get Your Love 1982" },
	{ "name" : "Andrea True - NY, You Got Me Dancing 1977" },
	{ "name" : "Andrea True - What's Your Name, What's Your Number 1977" },
	{ "name" : "Ann Margret - Everybody Needs Somebody Sometimes (Larry played Instr. 1981" },
	{ "name" : "Anthony & The Camp - What I Like (12&quot;) 1986" },
	{ "name" : "Anthony White - Block Party (Inst.) 1977" },
	{ "name" : "Archie Bell - Anytime Is Right 1981" },
	{ "name" : "Aretha Franklin - Freeway Of Love (12&quot;) 1985" },
	{ "name" : "Aretha Franklin - Get It Right 1983" },
	{ "name" : "Aretha Franklin - Who's Zooming Who (12&quot;) 1985" },
	{ "name" : "Arpeggio - Love & Desire 1979" },
	{ "name" : "Ashford & Simpson - Don't Cost You Nothin' 1978" },
	{ "name" : "Ashford & Simpson - Outta The World (12&quot;) 1985" },
	{ "name" : "Ashford & Simpson - Stay Free (LP) 1979" },
	{ "name" : "Atlantis - Keep On Movin' & Groovin' 1982" },
	{ "name" : "Atmosphere - Atmosphere Strut 1976 Sojka and Pike on Elite" },
	{ "name" : "Atmosphere - Dancing In Outer Space 1981" },
	{ "name" : "Atmosphere - Disco Juice 1976" },
	{ "name" : "Atmosphere - Spaced Out 1976" },
	{ "name" : "Attitude - Love Me Tonight 1983" },
	{ "name" : "Aurra - Checking You Out 1982 Salsoul" },
	{ "name" : "Aurra - Make Up Your Mind 1981" },
	{ "name" : "Ava Cherry - You Never Loved Me 1980" },
	{ "name" : "B Beat Girls - For The Same Man 1982" },
	{ "name" : "B.T. Taylor - You Can't Have Your Cake (& Eat It Too) 1982" },
	{ "name" : "Baby'0 - In The Forest 1980" },
	{ "name" : "Bad Girls - Too Through 1981" },
	{ "name" : "Bananarama - Cruel Summer (12&quot; Mix) 1984" },
	{ "name" : "Barbara Fowler - Come And Get My Lovin' 1984" },
	{ "name" : "Barbara Mason - Another Man 1984" },
	{ "name" : "Barbara Pennington - 24 Hours A Day (12&quot; Vers.) 1977" },
	{ "name" : "Barbara Streisand - Promises (LP) 1981" },
	{ "name" : "Basement Boys - Love Don't Live Here Anymore (12&quot; or Comp. LP) 1987" },
	{ "name" : "BBCS&A - Rock Shock 1982" },
	{ "name" : "Bell & James - Livin' It Up 1978" },
	{ "name" : "Ben E. King - Music Trance 1980" },
	{ "name" : "Bert Reid - Groovin' With You (Levan 12&quot; Mix) 1984" },
	{ "name" : "Betty Wright - One Step Up, Two Steps Back 1984" },
	{ "name" : "Beverly Johnson - Can't You Feel It (LP) 1979" },
	{ "name" : "Bill Brandon - We Fell In Love While Dancing 1978" },
	{ "name" : "Billie - Nobody's Bizness 1983 Fleetwood rds" },
	{ "name" : "Billy Frazier - Billy Who? 1980" },
	{ "name" : "Billy Nichols - Give Your Body Up To The Music 1979 Levan mix on West End rds" },
	{ "name" : "Billy Ocean - Love Zone (12&quot;) 1986" },
	{ "name" : "Billy Ocean - Nights (Feel Like Getting Down) (12&quot; Remix) 1981" },
	{ "name" : "Billy Ocean - Stay The Night (12&quot; Vers.) 1981" },
	{ "name" : "Bionic Boogie - Risky Changes 1978" },
	{ "name" : "Black Ivory - Mainline (12&quot;) 1979 P Adams and L Burgess" },
	{ "name" : "Black Light Orchestra - Touch Me, Take Me 1977" },
	{ "name" : "Black Mamba - Vicious (Levan 12&quot; Mix) 1984 Garage rds" },
	{ "name" : "Blackbyrds - Happy Music 1976 Donald Byrd" },
	{ "name" : "Blackwell - Boogie Down & Mess Around 1978" },
	{ "name" : "Blancmanage - Feel Me 1982" },
	{ "name" : "Blaze - If You Should Need A Friend (12&quot;) 1987" },
	{ "name" : "Blondie - Rapture 1981" },
	{ "name" : "Bo Kool - Love Money 1982 inspired 'Love Honey Love Heartache' On Tania records, UK track" },
	{ "name" : "Bob-A-Rela - Spend The Night 1979" },
	{ "name" : "Bob-A-Rela - Stop 1979" },
	{ "name" : "Bobbettes - Love Rhythm 1981" },
	{ "name" : "Bobby Thurston - Check Out This Groove 1980" },
	{ "name" : "Bobby Thurston - You Got What It Takes 1980" },
	{ "name" : "Bohannon - Let's Start The Dance 1978" },
	{ "name" : "Boney M - Daddy Cool 1977" },
	{ "name" : "Bonnie Boyer - Got To Give In To Love 1979" },
	{ "name" : "Booker T - Don't Stop Your Love (12&quot; Remix) 1981" },
	{ "name" : "Boris Badenough - Hey Rocky (12&quot;) 1986" },
	{ "name" : "Brainstorm - Hot For You 1979" },
	{ "name" : "Brainstorm - Lovin' Is Really My Game 1977" },
	{ "name" : "Brainstorm - We're On Our Way Home 1978" },
	{ "name" : "Brass Construction - Can You See The Light (12&quot; or LP) 1982 Randy Muller" },
	{ "name" : "Brass Construction - Changin' 1976" },
	{ "name" : "Brass Construction - Give & Take (12&quot;) 1985" },
	{ "name" : "Brass Construction - Walkin' The Line (12&quot;) 1983" },
	{ "name" : "Brass Construction - We Can Do It 1980" },
	{ "name" : "Brecker Brothers - Don't Stop The Music 1977" },
	{ "name" : "Brenda & Tabulations - Let's Go All The Way (Down) 1977" },
	{ "name" : "Brenda & Tabulations - Superstar 1977" },
	{ "name" : "Brenda Gooch - You And I Together 1980" },
	{ "name" : "Bruce Johnson - Pipeline 1979" },
	{ "name" : "Bruni Pagan - Fantasy 1979 Patrick Adams on .... Vanguard" },
	{ "name" : "Bruni Pagan - Lovers (LP) 1979" },
	{ "name" : "Buffalo Smoke - Stubborn Kind Of Fellow 1978" },
	{ "name" : "Bumble Bee Unlimited - Love Bug (Original Red Greg 12&quot;) 1976 Greg Carmichael" },
	{ "name" : "Bunny Sigler - By The Way You Dance 1978" },
	{ "name" : "CJ & Co - Devil's Gun 1977" },
	{ "name" : "C-Bank - One More Shot 1983 John Robie" },
	{ "name" : "C-Brand - Wired For Games 1982" },
	{ "name" : "Cameron - All That's Good To Me 1981" },
	{ "name" : "Cameron - Boogie's Gonna Get Ya 1981" },
	{ "name" : "Cameron - Let's Get It Off 1980" },
	{ "name" : "Cameron - The Magic Of You 1980" },
	{ "name" : "Candi Staton - When You Wake Up Tomorrow 1979" },
	{ "name" : "Candido - Dancin' & Prancin' 1979 Salsoul" },
	{ "name" : "Candido - Jingo 1979 Salsoul" },
	{ "name" : "Candido - Thousand Fingerman 1979 Salsoul" },
	{ "name" : "Capricorn - Capricorn 1980" },
	{ "name" : "Captain Rapp - Bad Times (I Can't Stand It) 1983" },
	{ "name" : "Captain Rapp - I Can't Stand It (12&quot; - 2nd Press) 1986" },
	{ "name" : "Carl Bean - I Was Born This Way (12&quot;) 1987" },
	{ "name" : "Carl Bean - I Was Born This Way (Orig. Motown 12&quot;) 1978" },
	{ "name" : "Carly Simon - Why 1982 Atlantic WEA" },
	{ "name" : "Carol Douglas - You're Not So Hot (12&quot; or LP Vers.) 1983 Next Plateau" },
	{ "name" : "Carol Hahn - Do Your Best 1982" },
	{ "name" : "Carol Williams - Can't Get Away From Your Love 1982" },
	{ "name" : "Carol Williams - No One Can Do It Like You 1981" },
	{ "name" : "Carol Williams - You've Reached The Bottom Line (12&quot;) 1983" },
	{ "name" : "Carolyn Harding - Gonna Get Your Love (12&quot;) 1985" },
	{ "name" : "Carolyn Harding - Memories (12&quot;) 1986" },
	{ "name" : "Carolyn Harding - Moving On (12&quot;) 1987" },
	{ "name" : "Carolyn Porter - I Said It And I Meant It (12&quot;) 1987" },
	{ "name" : "Carrie Lucas - I Gotta Keep Dancin (Original Vers.) 1977" },
	{ "name" : "Cat Stevens - Was Dog A Doughnut 1977" },
	{ "name" : "Celi Bee - Superman 1977" },
	{ "name" : "Central Line - Don't Tell Me 1981" },
	{ "name" : "Central Line - Walking Into Sunshine (12&quot; Levan Remix) 1981" },
	{ "name" : "Cerrone - Cerrone's Paradise 1977" },
	{ "name" : "Cerrone - Je Suis Music 1978" },
	{ "name" : "Cerrone - Supernature 1978" },
	{ "name" : "Cerrone - Take Me 1977" },
	{ "name" : "Cerrone feat. Jocelyn Brown - Cherry Tree 1980" },
	{ "name" : "Chaka Khan - I Know You, I Live You (LP) 1981" },
	{ "name" : "Chaka Khan - Tearin' It Up (12&quot; Levan Remix) 1983" },
	{ "name" : "Change - Paradise 1981" },
	{ "name" : "Change - The Very Best In You 1982" },
	{ "name" : "Change - This Is Your Time 1983" },
	{ "name" : "Chantel Curtis - Get Another Love 1979" },
	{ "name" : "Chantel Curtis - Hit Man (LP) 1979" },
	{ "name" : "Charlie Calello Orchestra - Sing Sing Sing 1979" },
	{ "name" : "Charo - Dance A Little Bit Closer 1977 Salsoul" },
	{ "name" : "Chas Jankel - Glad To Know You 1982" },
	{ "name" : "Chemise - She Can't Love You 1981" },
	{ "name" : "Cher - Take Me Home 1979" },
	{ "name" : "Cheri - Small Town Lover 1983" },
	{ "name" : "Cheri - Star Struck 1982" },
	{ "name" : "Cheryl Lynn - In The Night 1981" },
	{ "name" : "Cheryl Lynn - Keep It Hot (12&quot;) 1979" },
	{ "name" : "Cheryl Lynn - Love Bomb 1979" },
	{ "name" : "Cheryl Lynn - Star Love 1977" },
	{ "name" : "Cheryl Lynn - You Saved My Day 1978" },
	{ "name" : "Cheyne - Call Me Mr. Telephone (12&quot;) 1985" },
	{ "name" : "Chi-Lites - My First Mistake 1977" },
	{ "name" : "Chic - Chic Cheer 1978" },
	{ "name" : "Chicago - Street Player (12&quot; Mix) 1979 Columbia reds" },
	{ "name" : "Chip E. - Like This (12&quot;) 1985" },
	{ "name" : "Chocolette - It's That East Street Beat (12&quot;) 1985" },
	{ "name" : "Choice 4 - Come Down To Earth 1977" },
	{ "name" : "Circle City Band - Magic 1983" },
	{ "name" : "Circuit - A Little Help From My Friends (12&quot;) 1985" },
	{ "name" : "Circuit - Release The Tension 1984" },
	{ "name" : "Cissy Houston - Think It Over 1978" },
	{ "name" : "Citispeak - I Don't Need Your Handouts 1984" },
	{ "name" : "Citispeak - Rock To Rock 1983" },
	{ "name" : "CJ & Co - We Got Our Own Thing 1977" },
	{ "name" : "Class Action - Weekend (12&quot; Levan Remix) 1981 Sleeping Bag rds" },
	{ "name" : "Claudja Barry - Down & Counting (12&quot;) 1986" },
	{ "name" : "Claudja Barry - Johnny Please Come Home 1978" },
	{ "name" : "Claudja Barry - Sweet Dynamite 1977" },
	{ "name" : "Clausell - Don't Let It Be Crack (12&quot;) 1986 Joe Clausell ???" },
	{ "name" : "Coffee - Purpose (LP) 1982" },
	{ "name" : "Colonel Abrams - How Soon We Forget (12&quot; Remix) 1987" },
	{ "name" : "Colonel Abrams - I'm Not Gonna Let (12&quot;) 1986" },
	{ "name" : "Colonel Abrams - Music Is The Answer 1984" },
	{ "name" : "Colonel Abrams - Over & Over (12&quot;) 1986" },
	{ "name" : "Colonel Abrams - Speculation (12&quot;) 1985" },
	{ "name" : "Colonel Abrams - Trapped (12&quot;) 1985" },
	{ "name" : "Colors - Am I Gonna Be The One (12&quot; Dub Vers.) 1983" },
	{ "name" : "Colors - Pay Me Back My Love (12&quot;) 1986" },
	{ "name" : "Columbus Circle - If You Read My Mind 1982" },
	{ "name" : "Conquest - Give It To Me 1981" },
	{ "name" : "Conversion - Let's Do It 1981 --> Leroy Burgess" },
	{ "name" : "Conversion - Sweet Thing 1982" },
	{ "name" : "Cookie - You Can't Judge A Book By It's Cover 1982" },
	{ "name" : "Cory Daye - Pow Wow 1978" },
	{ "name" : "Crown Heights Affair - Dancin' 1977" },
	{ "name" : "Crown Heights Affair - Don't Wanna Change You 1980" },
	{ "name" : "Crown Heights Affair - I See The Light 1980" },
	{ "name" : "Crown Heights Affair - Say A Prayer For Two 1978" },
	{ "name" : "Cuba Gooding - Happiness Is Just Around The Bend 1983 Streetwise rds" },
	{ "name" : "Cultural Vibe - Mind Games (12&quot;) (Not the same record as Quest) 1986 Easystreet reds" },
	{ "name" : "Curtis Hairston - I Want You (All Tonight) 1983" },
	{ "name" : "Curtis Hairston - I Want You All Tonight (12&quot;) 1985" },
	{ "name" : "Curtis Hairston - We All Are One 1984" },
	{ "name" : "Curtis Mayfield - Tell Me (How Ya Liked To Be Loved) 1979" },
	{ "name" : "Curtis Mayfield - What Is My Woman For? 1979" },
	{ "name" : "D Train - Keep On 1982 Prelude" },
	{ "name" : "D Train - Music 1983 Prelude" },
	{ "name" : "D Train - Walk On By 1982 Prelude" },
	{ "name" : "D Train - You're The One For Me 1981 Prelude" },
	{ "name" : "D.C. LaRue - Cathedrals 1977" },
	{ "name" : "D.C. LaRue - Let Them Dance 1978" },
	{ "name" : "D.D. Sounds - Cafe 1978" },
	{ "name" : "Dan Hartman - I Can Dream About You (Levan 12&quot; Remix) 1984" },
	{ "name" : "Dan Hartman - Love Strong 1979" },
	{ "name" : "Dan Hartman - Relight My Fire 1978" },
	{ "name" : "Dan Hartman - We Are The Young (Levan 12&quot; Remix) 1984" },
	{ "name" : "David Bowie - Let's Dance (12&quot;) 1983" },
	{ "name" : "David Christie - Don't Stop Me, I Like It 1978" },
	{ "name" : "David Williams - Come On Down, Boogie People 1977" },
	{ "name" : "Dazz Band - Let It All Blow (12&quot; Mix) 1984" },
	{ "name" : "Debbie Jacobs - Don't You Want My Love 1979" },
	{ "name" : "Dee Dee Bridgewater - Bad For Me (Ext. 12&quot; Mix) 1979" },
	{ "name" : "Dee Edwards - Put Your Love On The Line 1980" },
	{ "name" : "Delegation - Heartache No. 9 1980" },
	{ "name" : "Denise McCann - Tattoo Man 1976" },
	{ "name" : "Dennis Coffey - Wings Of Fire 1977" },
	{ "name" : "Denroy Morgan - Happy Feeling 1982 Becket rds" },
	{ "name" : "Deodato - Are You For Real 1984" },
	{ "name" : "Deodato - Keep It In The Family (LP) 1982" },
	{ "name" : "Deodato - Keep On Movin' 1982" },
	{ "name" : "Deodato - Night Cruiser 1980" },
	{ "name" : "Deodato - Whistle Bump 1978" },
	{ "name" : "Desmond Child & Rouge - Our Love Is Insane (Ext. 12&quot; Mix) 1979" },
	{ "name" : "Dexter Wansel - Disco Lights 1977 PIR" },
	{ "name" : "Dexter Wansel - Life On Mars" },
	{ "name" : "Dhar Braxton - Jump Back (12&quot;) 1986 Sleeping Bag rds" },
	{ "name" : "Diamond Touch - Love Line (12&quot;) 1985" },
	{ "name" : "Diana Ross - Love Hangover 1976" },
	{ "name" : "Diana Ross - Once In The Morning (LP) 1979" },
	{ "name" : "Diana Ross - That's How You Start Over (LP) 1983" },
	{ "name" : "Diana Ross - Work That Body (12&quot; Version) 1982" },
	{ "name" : "Dianne Marie - I've Waited Much Too Long 1982" },
	{ "name" : "Dinosaur - Kiss Me Again 1978 Sire rds" },
	{ "name" : "Dinosaur L - Corn Belt (Levan Mix; Comp. LP) 1986 Sleeping Bag rds" },
	{ "name" : "Dinosaur L - Go Bang 1983 Sleeping Bag rds" },
	{ "name" : "Direct Current - Everybody Here Must Party 1979" },
	{ "name" : "Don Ray - Got To Have Loving 1978" },
	{ "name" : "Don Ray - Standing In The Rain 1978" },
	{ "name" : "Donald Byrd - Love Has Come Around 1981" },
	{ "name" : "Donald Fagen - New Frontier 1982" },
	{ "name" : "Donna McGhee - It Ain't No Big Thing 1979" },
	{ "name" : "Donna Summer - Bad Girls 1979" },
	{ "name" : "Donna Summer - Hot Stuff 1979" },
	{ "name" : "Donna Washington - 'Scuse Me, While I Fall In Love 1981 Salsoul" },
	{ "name" : "Double Exposure - Every Man Has Got To Carry His Own Weight	1976 Salsoul" },
	{ "name" : "Double Exposure - I Declare War 1978 Salsoul" },
	{ "name" : "Double Exposure - I Got The Hots For You (12&quot; Mix) 1979 Salsoul" },
	{ "name" : "Double Exposure - My Love Is Free 1977 Salsoul" },
	{ "name" : "Double Exposure - Ten Percent 1976 Salsoul" },
	{ "name" : "Dynamic Superiors - Nowhere To Run 1977" },
	{ "name" : "Earons - Land Of Hunger 1984" },
	{ "name" : "Earth, Wind & Fire - Side By Side (LP) 1983" },
	{ "name" : "Eastbound Expressway - Never Let Go 1979" },
	{ "name" : "Ecstacy, Passion & Pain - If You Want Me 1981 Roy B rds" },
	{ "name" : "Ecstacy, Passion & Pain - Touch And Go 1976" },
	{ "name" : "Eddie Drennon - Would You Dance To My Music 1977" },
	{ "name" : "Eddie Kendricks - Ain't No Smoke Without Fire 1978" },
	{ "name" : "Eddie Kendricks - Goin' Up In Smoke 1976 Motown rds" },
	{ "name" : "Eddy Grant - Living On The Frontline 1978" },
	{ "name" : "Eddy Grant - Nobody's Got Time 1980" },
	{ "name" : "Eddy Grant - Walking On Sunshine (Ext. 12&quot; Mix) 1979 Ice rds" },
	{ "name" : "Eddy Rosemond - Funk It 1979" },
	{ "name" : "Edgar Winter Group - Above & Beyond 1979" },
	{ "name" : "Ednah Holt - Serious, Serious Space Party (Levan 12&quot; Mix) 1981 West End rds" },
	{ "name" : "Edwin Birdsong - Rapper Dapper Snapper 1980 Salsoul rds" },
	{ "name" : "El Coco - Cocomotion 1977" },
	{ "name" : "El Coco - Dancing In Paradise 1978" },
	{ "name" : "El Coco - Let's Get It Together 1976" },
	{ "name" : "Eleanor Mills - Mr. Right (12&quot;) 1987" },
	{ "name" : "Electric Mind - Zwei 1983" },
	{ "name" : "Eloise Whitaker - Don't Turn Your Back On Me 1981" },
	{ "name" : "Empire - Freakman 1981" },
	{ "name" : "Empress - Dyin' To Be Dancin' 1981 Prelude rds" },
	{ "name" : "Empress - Take A Risk 1982 Prelude rds" },
	{ "name" : "Erasure - Sometimes (12&quot; Remix) 1987" },
	{ "name" : "Erotic Drum Band - Plug Me To Death 1978" },
	{ "name" : "ESG - Moody 1981 99 rds" },
	{ "name" : "Esther Williams - I'll Be Your Pleasure (Levan Remix 12&quot; or LP) 1981" },
	{ "name" : "Esther Williams - You Gotta Let Me Show You 1976" },
	{ "name" : "Evelyn King - Your Personal Touch (12&quot;/LP) 1985" },
	{ "name" : "Evelyn Thomas - Heartless (12&quot;) 1985" },
	{ "name" : "Exodus - Together Forever 1979" },
	{ "name" : "Expose - Let Me Be The One (12&quot; Remix) 1987" },
	{ "name" : "Extras - Haven't Been Funked Enough 1979" },
	{ "name" : "Faith, Hope & Charity - You're My Piece Of Mind (Ext. 12&quot;	1976" },
	{ "name" : "Fancy - Come Inside (12&quot; Mix) 1984" },
	{ "name" : "Fantastic 4 - Got To Have Your Love 1977" },
	{ "name" : "Fantastic Aleems - Hooked On Your Love 1980" },
	{ "name" : "Fantasy - You're Too Late 1981" },
	{ "name" : "Farley Funk - Love Can't Turn Around (12&quot; Dub Mix) 1986" },
	{ "name" : "Farm Boy - Move (12&quot;) 1986" },
	{ "name" : "Fat Larry's Band - Act Like You Know 1982 --> see Whatnauts" },
	{ "name" : "Fat Larry's Band - Lookin' For Love 1979" },
	{ "name" : "Fatback Band - I Found Lovin' 1983" },
	{ "name" : "Fatback Band - Is This The Future (12&quot; Vers.) 1983" },
	{ "name" : "Fatback Band - Spanish Hustle 1976" },
	{ "name" : "Fatback Band - Take It Anyway You Want It 1981" },
	{ "name" : "Fatback Band - The Girl Is Fine 1983" },
	{ "name" : "Feel - I'd Like To 1982" },
	{ "name" : "Feel - Let's Rock Over & Over Again 1982 Sutra rds" },
	{ "name" : "Fern Kinney - Groove Me 1979" },
	{ "name" : "Final Edition - Betcha Can't Love Just Once 1980" },
	{ "name" : "Fingers, Inc. - Can You Feel It (Comp. LP) 1987" },
	{ "name" : "Fingers, Inc. - Mystery Of Love (12&quot;) 1987" },
	{ "name" : "Fingers, Inc. - Never No More Lonely (LP) 1987" },
	{ "name" : "First Choice - Breakaway 1980 Salsoul rds" },
	{ "name" : "First Choice - Doctor Love 1977 Goldmind rds" },
	{ "name" : "First Choice - Double Cross (Levan Remix) 1979 Salsoul rds" },
	{ "name" : "First Choice - Let No Man Put Asunder (Remix) 1982 Salsoul rds" },
	{ "name" : "First Choice - Love Thang 1978 Goldmind rds" },
	{ "name" : "First Love - Don't Say Goodnight 1980" },
	{ "name" : "Five Special - Why Leave Us Alone 1979" },
	{ "name" : "Flakes - Sugar Frosted Lover 1980" },
	{ "name" : "Fleetwood Mac - Little Lies (12&quot; Remix) 1987" },
	{ "name" : "Flower - Classical Love 1979" },
	{ "name" : "Fonda Rae - Heobah 1983 Posse rds" },
	{ "name" : "Fonda Rae - Over Like A Fat Rat 1982 Vanguard rds" },
	{ "name" : "Foxy - Tena's Song 1978" },
	{ "name" : "France Joli - Gonna Get Over You 1982 Prelude rds" },
	{ "name" : "France Joli - The Heart To Break The Heart 1980 Prelude rds" },
	{ "name" : "Fred Fowler - Girl You Need A Change Of Mind (12&quot;) (Kendricks Remake) 1986" },
	{ "name" : "Freda Payne - I'll Do Anything For You (12&quot; Vers.) 1978" },
	{ "name" : "Freda Payne - Love Magnet 1977" },
	{ "name" : "Free Life - There's Something Better 1979" },
	{ "name" : "Freeez - I.O.U. 1983" },
	{ "name" : "Fresh Band - Come Back Lover 1984" },
	{ "name" : "Frida - I Know There's Something Goin' On 1982" },
	{ "name" : "Frisky - You Got Me Dancing In My Sleep 1979" },
	{ "name" : "Aretha Franklin - Jump To It 1983" },
	{ "name" : "Front Page Orchestra - Love Insurance 1979" },
	{ "name" : "Frontline Orchestra - Don't Turn Your Back On Me 1981" },
	{ "name" : "Full Circle - Workin' Up A Sweat (12&quot;) 1986" },
	{ "name" : "Full House - Communicate (12&quot;) 1986" },
	{ "name" : "Funk Deluxe - This Time 1984" },
	{ "name" : "Funk Fusion Band - Can You Feel It 1982" },
	{ "name" : "Funkapolitan - As Time Goes By 1982" },
	{ "name" : "Gary Criss - Rio De Janiero 1978 Salsoul rds" },
	{ "name" : "Gary's Gang - Let's Love Dance Tonight 1979" },
	{ "name" : "Gayle Adams - Love Fever (12&quot;) 1981" },
	{ "name" : "Gayle Adams - Stretchin' Out 1980" },
	{ "name" : "Gayle Adams - You Brought It On Yourself 1980" },
	{ "name" : "Gayle Adams - Your Love Is A Life Saver 1980" },
	{ "name" : "Gaz - Sing Sing 1978 Salsoul rds" },
	{ "name" : "Gene Chandler - Get Down 1978" },
	{ "name" : "Gene Dunlap - Take My Love 1981" },
	{ "name" : "General Johnson - Can't Nobody Love Me Like You Do 1978" },
	{ "name" : "George Duke - I Want You For Myself 1979" },
	{ "name" : "George Kranz - Din Daa Daa (Original 12&quot; Mix) 1984" },
	{ "name" : "George McCrae - Love In Motion 1977" },
	{ "name" : "Geraldine Hunt - Can't Fake The Feeling 1980" },
	{ "name" : "Gibson Brothers - Cuba 1979" },
	{ "name" : "Gibson Brothers - Oh What A Life 1980" },
	{ "name" : "Gino Soccio - Hold Tight 1981" },
	{ "name" : "Gino Soccio - I Wanna Take You There Now 1980" },
	{ "name" : "Gino Soccio - It's Alright 1982" },
	{ "name" : "Gino Soccio - Try It Out 1981" },
	{ "name" : "Gino Soccio - You Move Me (LP) 1982" },
	{ "name" : "Gino Soccio - Dancer 1979" },
	{ "name" : "Giorgio - I Wanna Rock You 1979" },
	{ "name" : "Girls Can't Help It - Baby Doll 1982" },
	{ "name" : "Gladys Knight & The Pips - Save The Overtime For Me (12&quot; Vers.) 1983" },
	{ "name" : "Gladys Knight - It's A Better Than Good Time 1978" },
	{ "name" : "Gladys Knight - Love Is Always On Your Mind 1977" },
	{ "name" : "Glass - Let Me Feel Your Heartbeat 1982 West End rds" },
	{ "name" : "Gloria Gaynor - Let's Make A Deal 1976" },
	{ "name" : "Gloria Gaynor - Let's Mend What's Been Broken (LP or 12&quot;) 1981" },
	{ "name" : "Goldie Alexander - Show You My Love 1982" },
	{ "name" : "Goody Goody - It Looks Like Love 1978 Atlantic --> Montana" },
	{ "name" : "Goody Goody - Let Me Work On You 1982 Black Sun rds" },
	{ "name" : "Grace Jones - Do Or Die 1978" },
	{ "name" : "Grace Jones - Don't Mess With The Messer 1979" },
	{ "name" : "Grace Jones - Feel Up (Levan Remix) 1982 Island rds" },
	{ "name" : "Grace Jones - I'm Not Perfect (But I'm Perfect For You) (12&quot;) 1986" },
	{ "name" : "Grace Jones - La Vie En Rose 1977" },
	{ "name" : "Grace Jones - My Jamaican Guy 1978" },
	{ "name" : "Grace Jones - Nipple To The Bottle 1982" },
	{ "name" : "Grace Jones - On Your Knees 1979" },
	{ "name" : "Grace Jones - Pull Up To The Bumper 1981" },
	{ "name" : "Grace Jones - Slave To The Rhythm/The Fashion Show/Ladies & Gentlemen (all 1985 1985" },
	{ "name" : "Grace Jones - Sorry 1976" },
	{ "name" : "Grace Jones - Warm Leatherette 1980" },
	{ "name" : "Greg Phillinganes - Behind The Mask (12&quot;) 1985" },
	{ "name" : "Gregg Diamond - Danger 1979" },
	{ "name" : "Gregg Diamond - Star Cruising 1978" },
	{ "name" : "Grey & Hanks - Dancin' 1979" },
	{ "name" : "Gunchback Boogie Band - Funn 1982" },
	{ "name" : "Gwen Guthrie - Hopscotch (LP Version) 1983 Island rds" },
	{ "name" : "Gwen Guthrie - It Should Have Been You 1982" },
	{ "name" : "Gwen Guthrie - Outside In The Rain (Levan 12&quot; Remix) 1986" },
	{ "name" : "Gwen Guthrie - Padlock (Levan Remix - EP) 1985" },
	{ "name" : "Gwen Guthrie - Peanut Butter (LP Version; Levan remix released in 1985) 1983" },
	{ "name" : "Gwen Guthrie - Seventh Heaven (LP Version) 1983" },
	{ "name" : "Gwen Guthrie - Seventh Heaven/Getting Hot/Peanut Butter (Levan Remix - EP) 1985" },
	{ "name" : "Gwen Guthrie - They Long To Be Close To You (Levan 12&quot; Remix) 1987 Polydor rds" },
	{ "name" : "Gwen Guthrie - Ticket To Ride (Levan 12&quot; Remix) 1987 4th and Broadway rds" },
	{ "name" : "Gwen McCrae - Funky Sensation 1981" },
	{ "name" : "Gwen McCrae - Poyson 1981" },
	{ "name" : "Hanson & Davis - I'll Take You On (12&quot; Levan Mix) 1986 Fresh rds" },
	{ "name" : "Hanson & Davis - Tonight (Love Will Make It Right) (12&quot; Dub Mix) 1985" },
	{ "name" : "Harlequin Fours - Set It Off (12&quot; - female version) 1985" },
	{ "name" : "Harold Faltermeyer - Axel F (12&quot;) 1985" },
	{ "name" : "Harvey Mason - Groovin' You 1979 Arista rds" },
	{ "name" : "Heaven & Earth - I Really Love You 1981" },
	{ "name" : "Heaven 17 - Let Me Go 1983" },
	{ "name" : "Herbie Hancock - Tell Everybody 1979" },
	{ "name" : "Hercules - Seven Ways To Jack (12&quot;/Comp. LP) 1986" },
	{ "name" : "Hi-Gloss - You'll Never Know 1981" },
	{ "name" : "Hindsight - Stand Up (12&quot; Remix) 1987" },
	{ "name" : "Hot Cuisine - Who's Been Kissing You 1981" },
	{ "name" : "House People - Godfather Of House (12&quot;) 1986" },
	{ "name" : "Hugh Masekela - Don't Go Lose It, Baby 1984 Jive Africa" },
	{ "name" : "I Level - Give Me 1981" },
	{ "name" : "I Level - Minefield 1981" },
	{ "name" : "Ian Dury - Hit Me With Your Rhythm Stick 1978" },
	{ "name" : "Ian Dury - Reasons To Be Cheerful 1978" },
	{ "name" : "Ian Dury - Spasticus (Autisticus) 1981" },
	{ "name" : "Idris Muhammed - Could Heaven Ever Be Like This 1977" },
	{ "name" : "Imagination - Burnin' Up 1983" },
	{ "name" : "Imagination - Changes 1983" },
	{ "name" : "Imagination - Instinctual (12&quot; Remix) 1987" },
	{ "name" : "Imagination - Just An Illusin 1983" },
	{ "name" : "Imagination - Looking At Midnight (12&quot;) 1983" },
	{ "name" : "Imagination - State Of Love 1983" },
	{ "name" : "In-Sync - Sometimes Love Lets You Down (12&quot;) 1987" },
	{ "name" : "Indeep - Last Night A DJ Saved My Life 1983" },
	{ "name" : "Inner City Jam Band - What I Did For Love 1977" },
	{ "name" : "Inner Life - Ain't No Mountain High Enough (Garage Mix) 1981 Salsoul rds" },
	{ "name" : "Inner Life - I'm Caught Up 1979 Prelude rds" },
	{ "name" : "Inner Life - Let's Change It Up (12&quot;) 1985" },
	{ "name" : "Inner Life - Make It Last Forever (Levan Remix) 1981 Salsoul rds" },
	{ "name" : "Inner Life - Moment Of My Life 1982 Salsoul rds" },
	{ "name" : "Instant Funk - Body Shine (Levan Remix) 1979 Salsoul rds" },
	{ "name" : "Instant Funk - I Got My Mind Made Up (Levan Remix) 1979 Salsoul rds" },
	{ "name" : "Instant Funk - Just Because You'll Be Mine 1983 Salsoul rds" },
	{ "name" : "Instant Funk - Slap, Slap, Lickedy Lap (Levan Mix) 1979 Salsoul rds" },
	{ "name" : "Instant Funk - Why Don't You Think About Me 1979 Salsoul rds" },
	{ "name" : "Intrigue - Fly Girl (12&quot;) 1985" },
	{ "name" : "Invisible Man's Band - All Night Thing 1980 Island rds" },
	{ "name" : "Isaac Hayes - I Ain't Never 1980" },
	{ "name" : "Isaac Hayes - Moonlight Lovin' 1978" },
	{ "name" : "Isley Brothers - Harvest For The World 1976" },
	{ "name" : "Isley Brothers - Inside You (12&quot; or LP) 1981" },
	{ "name" : "J.M. Silk - I Can't Turn Around (12&quot;) 1987" },
	{ "name" : "J.M. Silk - Let The Music Take Control (12&quot;) 1987" },
	{ "name" : "J.M. Silk - Music Is The Key (12&quot;) 1985" },
	{ "name" : "J.R. Funk & Love Machine - Feel Good, Party Time 1980" },
	{ "name" : "Jackie Moore - How's Your Love Life Baby (Ext. 12&quot; Mix) 1979" },
	{ "name" : "Jacksons - The Hurt (LP Cut) 1984" },
	{ "name" : "Jago - Are You Going To Go 1983" },
	{ "name" : "Jaki Graham - Set Me Free (12&quot; Remix) 1987" },
	{ "name" : "Jakki - Sun Sun Sun 1976" },
	{ "name" : "Jamaica Boys - Spend Some Time (12&quot; Remix) 1987" },
	{ "name" : "Jamaica Girls - Need Somebody New (12&quot; Levan Remix) 1981 Sleeping Bag rds" },
	{ "name" : "Jamaica Girls - On The Move (12&quot;) 1986" },
	{ "name" : "Jamaica Girls - Rock The Beat 1982" },
	{ "name" : "James Brown - It's Too Funky In Here (12&quot;) 1979" },
	{ "name" : "James Brown - Living In America (12&quot;) 1985" },
	{ "name" : "James Wells - My Claim To Fame 1979" },
	{ "name" : "James Wells - True Love Is My Destiny 1978" },
	{ "name" : "Jammers - And You Know That 1982" },
	{ "name" : "Jammers - Be Mine Tonight 1983 Salsoul rds" },
	{ "name" : "Jan Leslie Holmes - I'm Your Superman (12&quot; Disco Mix Version) 1984" },
	{ "name" : "Janet Jackson - What Have You Done For Me Lately (12&quot;) 1986 A&M rds" },
	{ "name" : "Janice Christie - Heat Stroke (Levan 12&quot; Mix) 1986 Supertronics rds" },
	{ "name" : "Janice Christie - My Love Is Money 1984" },
	{ "name" : "Janice Christie - One Love (12&quot;) 1985" },
	{ "name" : "Janice Christie - Taking Me For Granted (12&quot;) 1987" },
	{ "name" : "Janice McClain - Smack Dab In The Middle (Levan Remix) 1980" },
	{ "name" : "Jean Carn - Time Waits For No One 1976" },
	{ "name" : "Jean Carn - Was That All It Was (Ext. 12&quot; Mix) 1979" },
	{ "name" : "Jeanette Lady Day - Come Let Me Love You 1981" },
	{ "name" : "Jeanette Thomas - Shake Your Body (12&quot;/Comp. LP) 1987" },
	{ "name" : "Jeff Lorber - Step By Step (12&quot;) 1985" },
	{ "name" : "Jeffrey Osborne - New Love 1982" },
	{ "name" : "Jeffrey Osborne - Plane Love (Levan 12&quot; Remix) 1984 A&M rds" },
	{ "name" : "Jeffrey Osborne - The Borderlines (Levan 12&quot; Remix) 1984 A&M rds" },
	{ "name" : "Jennifer Holliday - Hard Times For Lovers (Ext. 12&quot;) 1985" },
	{ "name" : "Jennifer Holliday - No Frills Love (Ext. 12&quot;) 1985" },
	{ "name" : "Jenny Burton - Bad Habits (12&quot;/LP) 1985" },
	{ "name" : "Jenny Burton - Remember What You Like 1983" },
	{ "name" : "Jimmy Bo Horne - Is It In 1980" },
	{ "name" : "Jimmy Bo Horne - Spank 1979" },
	{ "name" : "Jimmy BoHorne - Let's Do It (12&quot;) 1985" },
	{ "name" : "Jimmy Cliff - Peace Officer (Dub 12&quot; Version) 1982" },
	{ "name" : "Jimmy Ross - First True Love Affair (Levan 12&quot; Mix) 1981 Quality/RFC rds" },
	{ "name" : "Jimmy Ruffin - Falling In Love With You 1977" },
	{ "name" : "Jimmy Sabater - To Be With You 1976" },
	{ "name" : "Jimmy Williams - All Of My Lovin' 1983" },
	{ "name" : "Joan Armatrading - Kind Words (And A Real Good Heart) (12&quot;) 1986" },
	{ "name" : "Jocelyn Brown - Love's Gonna Get Ya (12&quot;) 1985" },
	{ "name" : "Joe Church - Don't You Wanna Be Mine (12&quot;) 1987" },
	{ "name" : "Joe Simon - Love Vibration 1978" },
	{ "name" : "Joe Tex - Ain't Gonna Bump No More 1977" },
	{ "name" : "Joe Thomas - Plato's Retreat 1978" },
	{ "name" : "John Davis - Night And Day 1976" },
	{ "name" : "John Rocca - I Want It To Be Real 1984" },
	{ "name" : "Johnny Dynell - Rhythm Of Love (12&quot;) 1985" },
	{ "name" : "Johnny Harris - Odyssey 1980" },
	{ "name" : "Jomanda - I'll Give It To You (12&quot;) 1987" },
	{ "name" : "Jones Girls - You Gonna Make Me Love Somebody Else (Ext. 12&quot; Mix) 1979" },
	{ "name" : "Joy - I Need Your Love 1983" },
	{ "name" : "Joyce Kennedy - Hold On For Love's Sake (12&quot;) 1985" },
	{ "name" : "Judy Cheeks - Mellow Lovin' 1978 Salsoul rds" },
	{ "name" : "Juggy Jones - Inside America 1976 Jupiter rds" },
	{ "name" : "Jungle Wonz - The Jungle (Comp. LP) 1986" },
	{ "name" : "Jungle Wonz - Time Marches On (12&quot;/Comp LP) 1987" },
	{ "name" : "Junior - Mama Used To Say 1982 Mercury UK rds" },
	{ "name" : "Junior - Not Tonight/Look What You've Done To Me (LP) 1985" },
	{ "name" : "Junior - Tell Me 1983 Mercury UK rds" },
	{ "name" : "Kano - Can't Hold Back Your Loving 1981 Emergency rds" },
	{ "name" : "Kano - I'm Ready 1980 Emergency rds" },
	{ "name" : "Karen Silver - Nobody Else 1981" },
	{ "name" : "Karen Silver - Set Me Free 1981" },
	{ "name" : "Karen Young - Detour 1982" },
	{ "name" : "Karen Young - Hot Shot 1978 West End rds" },
	{ "name" : "Karyn White - Facts Of Love (12&quot; Levan Remix) 1986" },
	{ "name" : "Kashif - Help Yourself To My Love 1983" },
	{ "name" : "Kashif - I Just Gotta Have You 1983" },
	{ "name" : "Kate Bush - Running Up That Hill (12&quot;) 1985" },
	{ "name" : "Kebekelektrik - War Dance 1978 Salsoul rds" },
	{ "name" : "Keith Barrow - Turn Me Up (Ext. 12&quot; Mix) 1979" },
	{ "name" : "Kellee Patterson - Turn On The Lights 1977" },
	{ "name" : "Keni Burke - You're The Best 1981" },
	{ "name" : "Key Of Dreams - Africa 1983" },
	{ "name" : "Kid Creole - Going Places 1981" },
	{ "name" : "Kid People - Life's A Party (12&quot;) 1985" },
	{ "name" : "King Errison - Manhattan Love Song 1977" },
	{ "name" : "Kinky Foxx - So Different 1980" },
	{ "name" : "Kleeer - Get Tough 1981" },
	{ "name" : "Kleeer - Keep Your Body Workin' 1978" },
	{ "name" : "Klein & MBO - Dirty Talk 1982" },
	{ "name" : "Klein & MBO - Wonderful 1982" },
	{ "name" : "Klinte Jones - In The Heat Of The Night 1984" },
	{ "name" : "Kokomo - Use Your Imagination 1976" },
	{ "name" : "Komiko - Feel Alright 1982" },
	{ "name" : "Konk - Konk Party (12&quot;) 1986" },
	{ "name" : "Konk - Your Life (12&quot;) 1986" },
	{ "name" : "Kool & The Gang - Fresh (12&quot; Remix) 1985" },
	{ "name" : "Kool & The Gang - Misled (12&quot; Remix) 1984" },
	{ "name" : "Kool & The Gang - Open Sesame (9 min. version) 1976" },
	{ "name" : "Koto - Japanese War Games 1983" },
	{ "name" : "Kraftwerk - Music Non-Stop (12&quot;) 1986" },
	{ "name" : "Kraftwerk - The Robots 1978" },
	{ "name" : "Kraftwerk - Trans Europe Express 1978" },
	{ "name" : "Kreamsicle - No News Is News 1984" },
	{ "name" : "Kurtis Blow - The Breaks 1980 Mercury US" },
	{ "name" : "L'Amour - Let's Make Love Tonight 1984" },
	{ "name" : "Lace - Can't Play Around (Levan 12&quot; Mix) 1982 Atlantic rds" },
	{ "name" : "Laid Back - The White Horse 1984" },
	{ "name" : "Lamont Dozier - Going Back To My Roots 1977" },
	{ "name" : "Larry Graham - Sooner Or Later 1982" },
	{ "name" : "Larry Page - Slinky Thighs 1977" },
	{ "name" : "Larry played) 1982" },
	{ "name" : "Laurice Hudson - Feel My Love 1982" },
	{ "name" : "LAX - All My Love 1980" },
	{ "name" : "Legacy - Don't Waste The Night (12&quot;) 1985" },
	{ "name" : "Lemelle - You Got Something Special 1982" },
	{ "name" : "Lemon - A-Freak-A 1978" },
	{ "name" : "Lenny Williams - Choosing You 1977" },
	{ "name" : "Lenny Williams - Please Don't Tempt Me 1977" },
	{ "name" : "Lenny Williams - You Got Me Running 1978" },
	{ "name" : "Leon Huff - I Ain't Jivin', I'm Jammin' 1981" },
	{ "name" : "Leon Love - Once Is Not Enough 1984" },
	{ "name" : "Les Lee - I'm The One You Want (12&quot;) 1985" },
	{ "name" : "Level 3 - Central Line 1982" },
	{ "name" : "Level 42 - Something About You (12&quot;) 1985" },
	{ "name" : "Level 42 - Starchild (12&quot;) 1985" },
	{ "name" : "Level 42 - World Machine (12&quot;) 1985" },
	{ "name" : "Lime - Agent 406 1981" },
	{ "name" : "Linda Clifford - Gypsy Lady (Ext. 12&quot; Vers.) 1978" },
	{ "name" : "Linda Clifford - Runaway Love (Ext. 12&quot; Version) 1978" },
	{ "name" : "Linda Evans - Don't You Need 1979" },
	{ "name" : "Linda Hopkins - It's In Your Blood 1977" },
	{ "name" : "Linda Taylor - You And Me Just Started 1982" },
	{ "name" : "Lipps, Inc. - All Night Dancing 1980" },
	{ "name" : "Liquid Liquid - Cavern 1984 99 rds" },
	{ "name" : "Lisa Lisa - I Wonder If I Take You Home (12&quot;/LP) 1985" },
	{ "name" : "Living In A Box - Living In A Box (12&quot;) 1987" },
	{ "name" : "Liz Torres - Can't Get Enough (12&quot;) 1987" },
	{ "name" : "Liz Torres - Mama's Boy (12&quot;) 1987" },
	{ "name" : "LNR - Work It To The Bone (12&quot;) 1987" },
	{ "name" : "Logg - I Know You Will (Levan 12&quot; Remix) 1981 Salsoul rds" },
	{ "name" : "Logg - You've Got That Something 1981 Salsoul rds" },
	{ "name" : "Loleatta Holloway - Catch Me On The Rebound 1978" },
	{ "name" : "Loleatta Holloway - Crash Goes Love 1984" },
	{ "name" : "Loleatta Holloway - Dreamin' 1976 Gold Mind rds" },
	{ "name" : "Loleatta Holloway - Greatest Performance Of My Life (Levan Remix) 1979 Gold Mind rds" },
	{ "name" : "Loleatta Holloway - Hit & Run (12&quot; Remix Vers.) 1977" },
	{ "name" : "Loleatta Holloway - I May Not Be There When You Want Me 1978" },
	{ "name" : "Loleatta Holloway - Love Sensation 1980 Salsoul rds" },
	{ "name" : "Loleatta Holloway - So Sweet (12&quot;) 1986" },
	{ "name" : "Loose Change - Straight From The Heart (12&quot; Mix) 1979" },
	{ "name" : "Loose Ends - Choose Me (12&quot;) 1985" },
	{ "name" : "Loose Joints - Is It All Over My Face (Levan Remix) 1978" },
	{ "name" : "Loose Joints - Tell You (Today) 1983" },
	{ "name" : "Lorraine Johnson - Feed The Flame 1978" },
	{ "name" : "Lorraine Johnson - The More I Get (Remake of Teddy - Larry played both) 1977" },
	{ "name" : "Love Club - Hot Summer Nights 1983" },
	{ "name" : "Love Committee - Law And Order 1978" },
	{ "name" : "Love Unlimited Orchestra - King Kong Theme 1977" },
	{ "name" : "Lucy Hawkins - Gotta Get Out Of Here 1978" },
	{ "name" : "M - Pop Muzik 1979" },
	{ "name" : "Machine - Is It Love 1980" },
	{ "name" : "Machine - Marisa 1979 RCA rds" },
	{ "name" : "Machine - 'There But For The Grace Of God Go I' 1979 RCA rds" },
	{ "name" : "Macho - I'm A Man 1978 Prelude rds" },
	{ "name" : "Made In The USA - Melodies 1977" },
	{ "name" : "Madhouse - Six (LP) 1987" },
	{ "name" : "Madleen Kane - Forbidden Love 1979" },
	{ "name" : "Madleen Kane - Rough Diamond 1978" },
	{ "name" : "Madleen Kane - You Can 1981" },
	{ "name" : "Madonna - Everybody 1982" },
	{ "name" : "Madonna - In The Groove 1984" },
	{ "name" : "Madonna - Open Your Heart (LP/12&quot;) 1986" },
	{ "name" : "Magazine 60 - Don Quichotte 1984" },
	{ "name" : "Mahogany - Ride On The Rhythm 1982" },
	{ "name" : "Mai Tai - History (12&quot;) 1985" },
	{ "name" : "Mai Tai - Hold Me (LP) 1986" },
	{ "name" : "Malcolm McClaren - Madam Butterfly 1984" },
	{ "name" : "Man Friday - Jump (12&quot; Levan Mix) 1986" },
	{ "name" : "Man Friday - Love Honey, Love Heartache (12&quot; Levan Mix) 1986 Bo Kool" },
	{ "name" : "Man Parrish - Hip Hop, Be Bop (Don't Stop) 1982" },
	{ "name" : "Marc Sadane - Exciting 1982" },
	{ "name" : "Marc Sadane - Sit Up 1981" },
	{ "name" : "Marcia Griffith - Electric Boogie 1983" },
	{ "name" : "Margie Joseph - Knockout 1982" },
	{ "name" : "Marianne Faithful - Why Did You Do It 1979" },
	{ "name" : "Marjie Joseph - Prophecy 1976" },
	{ "name" : "Mark IV - Rainy Days (12&quot;) 1985" },
	{ "name" : "Marsha Hunt - The Other Side Of Midnight (12&quot; Vers.) 1977" },
	{ "name" : "Marshall Jefferson - Move Your Body (House Music Anthem) (12&quot;) 1987" },
	{ "name" : "Martin Circus - Disco Circus 1978" },
	{ "name" : "Martin Circus - I've Got A Treat 1978" },
	{ "name" : "Mary Jane Girls - In My House (12&quot;) 1985" },
	{ "name" : "Mary Wells - Gigolo 1982" },
	{ "name" : "Mary Wells - These Arms 1981" },
	{ "name" : "Mass Production - Sun Dancer 1983" },
	{ "name" : "Mass Production - Welcome To Our World 1977" },
	{ "name" : "Master C&J - In The City (12&quot;) 1987" },
	{ "name" : "Matrix - Stay, I Need Your Love 1982" },
	{ "name" : "Matthew Wilder - Break My Stride (12&quot;) 1983" },
	{ "name" : "Maze - Twilight (12&quot;) 1985" },
	{ "name" : "Melba Moore - It's Been So Long (12&quot; Remix) 1987" },
	{ "name" : "Melba Moore - It's Been So Long (12&quot;) 1986" },
	{ "name" : "Melba Moore - Standing Right Here (Ext. Remix LP) 1979" },
	{ "name" : "Melba Moore - You Stepped Into My Life 1978" },
	{ "name" : "Merc & Monk - I Get Carried Away (Levan 12&quot; Remix) 1985" },
	{ "name" : "Metropolis - New York Is My Kind Of Twon 1978" },
	{ "name" : "Metropolis - The Greatest Show On Earth 1978" },
	{ "name" : "MFSB - Love Is The Message (14 min. Remix Vers.) 1981 PIR rds" },
	{ "name" : "MFSB - Mysteries Of The World 1980" },
	{ "name" : "MFSB - We Got The Time 1976" },
	{ "name" : "Michael Mauro - Susie Q 1980" },
	{ "name" : "Michael Wycoff - Still Got The Magic (Sweet Delight) 1982" },
	{ "name" : "Michael Wycoff - Tell Me Love 1983" },
	{ "name" : "Michael Zager Band - Love Express 1978" },
	{ "name" : "Michele - Disco Dance 1977" },
	{ "name" : "Michelle Freeman - Where'd You Get What You Got 1979" },
	{ "name" : "Michelle Goulet - Stop & Think (12&quot;) 1986" },
	{ "name" : "Michelle Wallace - It's Right 1982" },
	{ "name" : "Michelle Wallace - Jazzy Rhythm 1982" },
	{ "name" : "Mick Jagger - Lucky In Love (12&quot; Dub Remix) 1985" },
	{ "name" : "Midnight Rhythm - Workin' & Slavin' 1978" },
	{ "name" : "Midnight Star - Curious 1983" },
	{ "name" : "Midway - Set It Out 1984" },
	{ "name" : "Mighty Clouds Of Joy - Mighty High 1976" },
	{ "name" : "Mighty Pope - Sweet Blindness 1979" },
	{ "name" : "Miguel Brown - Symphony Of Love 1978" },
	{ "name" : "Mike Anthony - Why Can't We Live Together 1982" },
	{ "name" : "Mike Theodore - Cosmic Wind 1977" },
	{ "name" : "Mike Theodore Orchestra - The Bull 1978" },
	{ "name" : "Mikki - Dance Lover 1981" },
	{ "name" : "Mikki - Itching For Love 1981" },
	{ "name" : "Millie Scott - Every Little Bit Of You (12&quot; Remix) 1987" },
	{ "name" : "Millie Scott - Prisoner Of Love (12&quot;) 1986" },
	{ "name" : "Ministry - Work For Love 1982" },
	{ "name" : "Minnie Riperton - Adventures In Paradise 1976" },
	{ "name" : "Minnie Riperton - Stick Together (Ext. Mix) 1977" },
	{ "name" : "Modern Romance - Salsa Rapsody (Import 12&quot;) 1981" },
	{ "name" : "Moment Of Truth - Chained To Your Love 1977" },
	{ "name" : "Mona Lisa Young - Rock Me Down (12&quot;) 1985" },
	{ "name" : "Mona Rae - Do Me 1981" },
	{ "name" : "Montana - Who Needs Enemies (With A Friend Like You) 1983" },
	{ "name" : "Montana Sextet - Heavy Vibes 1982" },
	{ "name" : "Monyaka - Go Deh Yaka (Go To The Top) 1983" },
	{ "name" : "Morris Day - Color Of Success/The Character/The Oak Tree (All LP) 1985" },
	{ "name" : "Mtume - So You Wanna Be A Star 1980" },
	{ "name" : "Munich Machine - Party Light 1979" },
	{ "name" : "Murray Head - One Night In Bangkok (12&quot;) 1985" },
	{ "name" : "Musique - Push Push in the Bush --> Patrick Adams" },
	{ "name" : "Musique - Keep on Jumpin' --> Patrick Adams" },
	{ "name" : "N.V. - It's Alright 1983" },
	{ "name" : "N.V. - Let Me Do You 1984" },
	{ "name" : "Nancy Martin - Can't Believe 1982" },
	{ "name" : "Narada Michael Walden - The Nature Of Things (Levan 12&quot; Remix) 1985" },
	{ "name" : "Native - Love Ain't No Holiday 1984" },
	{ "name" : "Nature Zone - Porcupine 1976" },
	{ "name" : "New Birth - Deeper 1977" },
	{ "name" : "New York Community Choir - Express Yourself 1977" },
	{ "name" : "Nick Straker Band - A Little Bit Of Jazz 1981" },
	{ "name" : "Nick Straker Band - The Beat Inside (LP) 1981" },
	{ "name" : "Nile Rodgers - Land Of The Good Groove 1983" },
	{ "name" : "Nile Rodgers - State Your Mind/Stay Out Of The Light (Levan 12&quot; Remix) 1985" },
	{ "name" : "NJ Connection - Love Don't Come Easy 1981" },
	{ "name" : "Nona Hendryx - Keep It Confidential 1983" },
	{ "name" : "Nona Hendryx - Transformation 1983" },
	{ "name" : "Nona Hendryx - Why Should I Cry (12&quot; Remix) 1987" },
	{ "name" : "Norman Connors - Once I've Been There 1977" },
	{ "name" : "North End - Happy Days 1981" },
	{ "name" : "North End - Kind Of Love (Kind Of Life) 1979" },
	{ "name" : "Nu Shooz - I Can't Wait (12&quot;) 1985" },
	{ "name" : "Nu Shooz - I Can't Wait (12&quot;) 1986" },
	{ "name" : "Nuance - Love Ride (12&quot; Mix) 1984" },
	{ "name" : "O'Jays - Extraordinary Girl (LP) 1984" },
	{ "name" : "O'Jays - Put Our Heads Together 1983" },
	{ "name" : "Odyssey - Easy Come, Easy Go 1977" },
	{ "name" : "Odyssey - Inside Out 1982" },
	{ "name" : "Odyssey - Use It Up And Wear It Out 1980" },
	{ "name" : "One Way - Do Your Thang 1981" },
	{ "name" : "One Way - Music 1980" },
	{ "name" : "One Way - Shine On Me 1983" },
	{ "name" : "Originals - Down To Love Town 1976" },
	{ "name" : "Originals - Hurry Up And Wait 1976" },
	{ "name" : "Pam Todd - Let's Get Together 1979" },
	{ "name" : "Pamela Stanley - Coming Out Of Hiding 1984" },
	{ "name" : "Paradise Girls - Holding Back (12&quot; Dub Mix II) 1986" },
	{ "name" : "Passion - Don't Bring Back Memories 1980" },
	{ "name" : "Pat Benatar - Love Is A Battlefield 1983" },
	{ "name" : "Patrick Juvet - I Love America 1978" },
	{ "name" : "Patti Austin - Betcha Wouldn't Hurt Me 1981" },
	{ "name" : "Patti Austin - Honey For The Bees (Levan 12&quot; Remix) 1985" },
	{ "name" : "Patti Brooks - After Dark 1978" },
	{ "name" : "Patti Labelle - I'll Never, Never Give Up 1983" },
	{ "name" : "Patti Labelle - Music Is My Way Of Life 1979" },
	{ "name" : "Patti Labelle - Something Special (12&quot;) 1986" },
	{ "name" : "Patti Labelle - The Spirit's In It 1981" },
	{ "name" : "Paul Hardcastle - 19 (12&quot;) 1985" },
	{ "name" : "Paul Hardcastle - Don't Waste My Time (12&quot;) 1986" },
	{ "name" : "Paul Jabara - Pleasure Island 1978" },
	{ "name" : "Paul Simpson - Treat Her Sweeter (12&quot;) 1985" },
	{ "name" : "Paul Simpson Connection - Use Me, Lose Me 1982" },
	{ "name" : "Peech Boys - Come On, Come On (Levan 12&quot; Mix) 1984" },
	{ "name" : "Peech Boys - Don't Make Me Wait 1982" },
	{ "name" : "Peech Boys - Life Is Something Special (Levan Remix) 1983" },
	{ "name" : "Peech Boys - On A Journey (Levan Remix) 1983" },
	{ "name" : "Peech Boys - Warm Summer's Night (LP) 1983" },
	{ "name" : "Pennye Ford - Change Your Wicked Ways (12&quot; Remix) 1984" },
	{ "name" : "People's Choice - If I Knew Then What I Know Now 1980" },
	{ "name" : "People's Choice - You Ought To Be Dancin' 1980" },
	{ "name" : "Pete Shelley - Witness The Change 1981" },
	{ "name" : "Peter Brown - Disco Love Breakdown 1977" },
	{ "name" : "Peter Godwin - Emotional Disguise 1982" },
	{ "name" : "Peter Jacques Band - Fire Night Dance 1979" },
	{ "name" : "Philip Bailey - I Know 1983" },
	{ "name" : "Phreek - May My Love Be With You 1978" },
	{ "name" : "Phreek - Weekend 1978" },
	{ "name" : "Phyllis Nelson - I Like You (12&quot;) 1985" },
	{ "name" : "Phyllis St. James - Ain't No Turnin' Back (LP Cut) 1984" },
	{ "name" : "Pieces Of A Dream - Warm Weather 1981" },
	{ "name" : "Pilot - You Are The One 1984" },
	{ "name" : "Planet Patrol - Play At Your Own Risk 1982" },
	{ "name" : "Players Association - I Like It 1977" },
	{ "name" : "Players Association - Love Hangover (Inst. Remake of D. Ross' version) 1977" },
	{ "name" : "Pleasure Pump - Fantasize Me (12&quot;) 1987" },
	{ "name" : "Pockets - Come Go With Me 1977" },
	{ "name" : "Pointer Sisters - Automatic (12&quot; Remix) 1984" },
	{ "name" : "Pointer Sisters - Dare Me (12&quot;) 1985" },
	{ "name" : "Pointer Sisters - Happiness (Ext. 12&quot; Mix) 1979" },
	{ "name" : "Pointer Sisters - We've Got The Power 1980" },
	{ "name" : "Positive Force - We Got The Funk 1979" },
	{ "name" : "Positive People - This Feelin' 1981" },
	{ "name" : "Poussez - Boogie With Me 1979" },
	{ "name" : "Powerline - Journey 1981" },
	{ "name" : "Precious Wilson - I'll Be Your Friend (12&quot;) 1986" },
	{ "name" : "Pretty Poison - Catch Me (I'm Falling) (12&quot;) 1987" },
	{ "name" : "Prince - Controversy 1981" },
	{ "name" : "Prince - Just As Long As We're Together 1978" },
	{ "name" : "Prince - Sign Of The Times (12&quot;/LP) 1987" },
	{ "name" : "Princess & Starbreeze - The Drought (12&quot;/LP) 1987" },
	{ "name" : "Princess - Say I'm Your Number One (12&quot;) 1985" },
	{ "name" : "Private Possesion - Are You Wid It (12&quot;) 1986" },
	{ "name" : "Private Possession - This Time (12&quot;) 1986" },
	{ "name" : "Professor Funk - Visions (12&quot;) 1987" },
	{ "name" : "Project - Love Rescue 1979" },
	{ "name" : "Projection - Love Struck (12&quot;) 1987" },
	{ "name" : "Pure Energy - Breakaway 1981" },
	{ "name" : "Pure Energy - One Hot Night 1984" },
	{ "name" : "Pure Energy - Party On 1980" },
	{ "name" : "Pushe - Don't Take Your Love Away 1984" },
	{ "name" : "Q - The Voice Of Q 1982" },
	{ "name" : "Quando Quango - Love Tempo (12&quot;) 1987" },
	{ "name" : "Quartz - Beyond The Clouds 1978" },
	{ "name" : "Queen - Another One Bites The Dust 1980" },
	{ "name" : "Queen Samantha - Take A Chance (12&quot; Vers.) 1978" },
	{ "name" : "Quest - Mind Games (12&quot;) 1986" },
	{ "name" : "Rainbow Brown - Til You Surrender 1981 --> Patrick Adams" },
	{ "name" : "Rainy Davis - Sweetheart (12&quot;) 1986" },
	{ "name" : "Ralph McDonald - We Need More Calypso (12&quot;) 1985" },
	{ "name" : "Ramona Brooks - I Don't Want You Back 1980" },
	{ "name" : "Ramsey Lewis - This Ain't No Fantasy (12&quot; - Female Vocal Side) 1985" },
	{ "name" : "Randy Crawford - Don't Wanna Be Normal (LP) 1986" },
	{ "name" : "Raw Sex - Stop The War 1982" },
	{ "name" : "Raw Silk - Do It To The Music 1981 --> Nick Martinelli" },
	{ "name" : "Raw Silk - Just In Time And Space 1983" },
	{ "name" : "Raww - Don't You Try It 1984" },
	{ "name" : "Rebbie Jackson - Centipede (12&quot; Mix) 1984" },
	{ "name" : "Reel To Reel - Love Me Like This 1983" },
	{ "name" : "Relevation - Feel It 1981" },
	{ "name" : "Rene & Angela - Keep Running 1983" },
	{ "name" : "Revelation - Holdin' On 1982" },
	{ "name" : "Rhonda Parris - No No Love (12&quot;) 1986" },
	{ "name" : "Rhyze - Just How Sweet Is Your Love 1980" },
	{ "name" : "Rice & Beans Orchestra - You've Got Magic 1977" },
	{ "name" : "Richard J. Smith - Don't Go Walking Out That Door 1982" },
	{ "name" : "Rick Astley - Never Gonna Give You Up (12&quot; Remix) 1987" },
	{ "name" : "Rick James - Glow (12&quot;) 1985" },
	{ "name" : "Rick James - You And I 1978" },
	{ "name" : "Ripple - The Beat Goes On 1978" },
	{ "name" : "Rita Hart - Pardon Me Mister 1984" },
	{ "name" : "Ritchie Family - Alright On The Night (LP) 1982" },
	{ "name" : "Ritchie Family - I'll Do My Best For You 1982" },
	{ "name" : "Ritchie Family - Life Is Music 1977" },
	{ "name" : "Ritchie Family - Put Your Feet To The Beat 1979" },
	{ "name" : "Ritchie Family - Quiet Village 1977" },
	{ "name" : "Robert Gorl - Darling Don't Leave Me (Import 12&quot;) 1983" },
	{ "name" : "Roberta Flack - Lovin' You Is Such An Easy Thing To Do 1981" },
	{ "name" : "Rochelle Fleming - Love Itch (12&quot;) 1985" },
	{ "name" : "Rock Candy - I Got Love 1982" },
	{ "name" : "Rockers Revenge - Walking In Sunshine 1982" },
	{ "name" : "Rockers Revenge - Walking On Sunshine 1982" },
	{ "name" : "Rod - Just Keep On Walking 1982" },
	{ "name" : "Rod - Shake It Up (Do The Boogaloo) 1980" },
	{ "name" : "Rolling Stones - Missing You (12&quot; Vers.) 1978" },
	{ "name" : "Rome Jeffries - Good Love 1983" },
	{ "name" : "Ronnie Dyson - All Over Your Face 1983" },
	{ "name" : "Roschelle Fleming - I Know Just What You're After (12&quot;) 1987" },
	{ "name" : "Rose Royce - Do Your Dance 1977" },
	{ "name" : "Rose Royce - Love Me Right Now (12&quot;) 1985" },
	{ "name" : "Rose Royce - Still In Love 1982" },
	{ "name" : "Roundtree - Get On Up (Get On Down) 1978" },
	{ "name" : "Roundtree - Hit On You 1982" },
	{ "name" : "Roy Ayers - Don't Stop The Feeling 1979" },
	{ "name" : "Roy Ayers - Running Away 1977" },
	{ "name" : "Royal House - Can You Party (12&quot;/Comp. LP) 1987" },
	{ "name" : "Rufus - Any Love 1980" },
	{ "name" : "Rufus - One Million Kisses 1983" },
	{ "name" : "Russ Brown - Gotta Find A Way (12&quot;) 1986 --> Tee Scott" },
	{ "name" : "Salsoul Orchestra - 212 North Street 1981" },
	{ "name" : "Salsoul Orchestra - Don't Beat Around The Bush 1976" },
	{ "name" : "Salsoul Orchestra - How High (Levan Remix) 1979" },
	{ "name" : "Salsoul Orchestra - It's Good For The Soul 1976" },
	{ "name" : "Salsoul Orchestra - Love Break (Remix 12&quot;) 1982" },
	{ "name" : "Salsoul Orchestra - Magic Bird Of Fire 1977" },
	{ "name" : "Salsoul Orchestra - Run Away 1977" },
	{ "name" : "Salsoul Orchestra - Take Some Time Out For Love 1982" },
	{ "name" : "Salsoul Orchestra - You're Just The Right Size 1976" },
	{ "name" : "Salsoul Orchestrat w/ Loleatta Holloway - Seconds 1982" },
	{ "name" : "Samantha Fox - Touch Me (I Want Your Body) (12&quot;) 1986" },
	{ "name" : "Samson & Delilah - I Can Feel Your Love Slippin' Away 1984" },
	{ "name" : "Sandy Anderson - It's Over (I'm Through) (12&quot;) 1987" },
	{ "name" : "Sandy Mercer - Now That You're In 1979" },
	{ "name" : "Sandy Mercer - Play With Me, Lay With Me (12&quot; Vers.) 1978" },
	{ "name" : "Sandy Mercer - You Are My Love (12&quot; Vers.) 1978" },
	{ "name" : "Sarah Dash - Low Down, Dirty Rhythm 1983" },
	{ "name" : "Sarah Dash - Sinner Man 1979" },
	{ "name" : "Satin & Green - Spectacular 1982" },
	{ "name" : "Screamin' Rachel - Fun With Bad Boys (12&quot;) 1986" },
	{ "name" : "Seawind - Whatcha Doin'? 1980" },
	{ "name" : "Second Image - Can't Keep Holding On 1982" },
	{ "name" : "Secret Weapon - It Must Be The Music 1982" },
	{ "name" : "Serena - Get Your Body Up 1983" },
	{ "name" : "Sergio Mendes - I'll Tell You (Ext. 12&quot; Mix) 1979" },
	{ "name" : "Serious Intention - You Don't Know Pow Wow or Easy Street records?	(1986)" },
	{ "name" : "Seven Deadly Sins - Lust 1977" },
	{ "name" : "Shades Of Love - Keep In Touch (Body To Body) 1982" },
	{ "name" : "Shalamar - My Girl Loves Me (12&quot; Ext. Promo Only) 1985" },
	{ "name" : "Sharon Bailey - Cosmic Dust 1981" },
	{ "name" : "Sharon Brown - I Specialize In Love 1982" },
	{ "name" : "Sharon Paige - Tonight's The Night 1980" },
	{ "name" : "Sharon Redd - Beat The Street 1982" },
	{ "name" : "Sharon Redd - In The Name Of Love (LP) 1982" },
	{ "name" : "Sharon Ridley - Changin' (Closing Song at Garage) 1978" },
	{ "name" : "Sheryl Lee Ralph - In The Evening 1984" },
	{ "name" : "Shiela & B. Devotion - Spacer 1980" },
	{ "name" : "Shiela E. - A Love Bizarre (12&quot;/LP) 1985" },
	{ "name" : "Shiela Hilton - The Bed's Too Big Without You 1980" },
	{ "name" : "Shirley Lites - Heat You Up (Melt You Down) 1983" },
	{ "name" : "Side Effect - Always There 1976" },
	{ "name" : "Siedah Garrett - Do You Want It Right Now (12&quot;) 1985" },
	{ "name" : "Silver Convention - Dancing In The Aisles 1976" },
	{ "name" : "Silver Convention - Mission To Venus 1978" },
	{ "name" : "Silver Convention - Voodoo Woman 1977" },
	{ "name" : "Silvetti - Spring Rain 1977" },
	{ "name" : "Sinnamon - Thanks To You 1982" },
	{ "name" : "Siren - Open Up For Love 1979" },
	{ "name" : "Sister Sledge - Lost In Music 1979" },
	{ "name" : "Skatt Brothers - Walk The Night 1979" },
	{ "name" : "Skipworth & Turner - Can't Give Her Up (12&quot;) 1986" },
	{ "name" : "Skipworth & Turner - Thinking About Your Love (12&quot;) 1985" },
	{ "name" : "Skyy - First Time Around (Levan Remix) 1979" },
	{ "name" : "Skyy - Here's To You 1980" },
	{ "name" : "Skyy - Let Love Shine (LP) 1983" },
	{ "name" : "Skyy - Show Me The Way 1983" },
	{ "name" : "Skyy - Skyyzoo (Levan Remix) 1980" },
	{ "name" : "Skyy - Super Love 1980" },
	{ "name" : "Slave - Feel My Love 1981" },
	{ "name" : "Slave - Wait For Me 1981" },
	{ "name" : "Slimline - If You Can Dance, You Can Do It 1982" },
	{ "name" : "Sly Cabell - Feelin' Fine 1982" },
	{ "name" : "Smokey Robinson - And I Don't Love You (Levan 12&quot; - Larry played Dub) 1984" },
	{ "name" : "Sofonda C. - Pick It Up (12&quot;) 1987" },
	{ "name" : "Soft Cell - Tainted Love 1982" },
	{ "name" : "Softones - That Old Black Magic 1976" },
	{ "name" : "Somethin' Special - Come Make It Feel Good 1981" },
	{ "name" : "SOS Band - Take Love Where You Find It 1980" },
	{ "name" : "SOS Band - The Finest/Borrowed Love (LP) 1986" },
	{ "name" : "Soul Sonic Force - Planet Rock 1982" },
	{ "name" : "Southroad Connection - You Like It, We Love It 1978" },
	{ "name" : "Space - Carry On, Turn Me On 1977" },
	{ "name" : "Sparkle - Handsome Man (Levan Mix) 1980" },
	{ "name" : "Sparque - Let's Go Dancin' (Levan 12&quot; Remix) 1981" },
	{ "name" : "Sparque - Music Turns Me On 1982" },
	{ "name" : "Sparque - Take Some Time 1984" },
	{ "name" : "St. Tropez - Fill My Life With Love 1978" },
	{ "name" : "St. Tropez - One More Minute 1979" },
	{ "name" : "Stainless Steel - It All Comes Down To Love 1978" },
	{ "name" : "Stainless Steel - More Than Meets The Eye 1978" },
	{ "name" : "Staple Singers - Slippery People (12&quot; Mix) 1984" },
	{ "name" : "Stargard - Wear It Out (Ext. 12&quot; Mix) 1979" },
	{ "name" : "Starshine - All I Need Is You 1983" },
	{ "name" : "State Of Grace - That's When We'll Be Free 1982" },
	{ "name" : "Status IV - You Ain't Really Down 1983" },
	{ "name" : "Stephanie Mills - Medicine Song (12&quot; Remix) 1984" },
	{ "name" : "Stephanie Mills - Put Your Body In It (Ext. 12&quot; Mix) 1979" },
	{ "name" : "Stephanie Mills - You Can't Run From My Love (12&quot; Vers.) 1983" },
	{ "name" : "Steve Arrington - Dancin' In The Key Of Life (12&quot;/LP) 1985" },
	{ "name" : "Steve Arrington - Nobody Can Be You 1983" },
	{ "name" : "Steve Arrington - You Meet My Approval (LP) 1983" },
	{ "name" : "Steve Hurley - Jack Your Body (12&quot;) 1985" },
	{ "name" : "Steve Miller Band - Fly Like An Eagle 1976" },
	{ "name" : "Steve Miller Band - Macho City (12&quot; Vers.) 1982" },
	{ "name" : "Steve Shelto - Don't Give Your Love Away 1983" },
	{ "name" : "Stevie Nicks - Stand Back 1983" },
	{ "name" : "Stevie Wonder - As 1977" },
	{ "name" : "Stevie Wonder - Go Home (12&quot; Remix) 1985" },
	{ "name" : "Stevie Wonder - Love Light In Flight 1984" },
	{ "name" : "Sticky Fingers - Wastin' My Love 1978" },
	{ "name" : "Stimulation - Stimulation (12&quot;) 1985" },
	{ "name" : "Sting - If You Love Somebody, Set Them Free (12&quot; Remix) 1985" },
	{ "name" : "Stone - Time 1981 --> Tee Scott" },
	{ "name" : "Strafe - Set It Off 1984 --> Walter Gibbons" },
	{ "name" : "Strikers - Body Music (12&quot; Levan Remix) 1981" },
	{ "name" : "Strikers - Contagious 1982" },
	{ "name" : "Strikers - Inch By Inch 1981" },
	{ "name" : "Subject - Celebrate (12&quot;) 1986" },
	{ "name" : "Subject - The Magic, The Moment (12&quot;) 1985" },
	{ "name" : "Sun Palace - Rude Movements 1980" },
	{ "name" : "Supremes - High Energy 1976" },
	{ "name" : "Supremes - Let Yourself Go 1977" },
	{ "name" : "Suzi Lane - Harmony 1979" },
	{ "name" : "Suzy Q - Get On Up And Do It Again 1981" },
	{ "name" : "Suzy Q - With Your Love 1981" },
	{ "name" : "Sweet Cream - I Don't What I'd Do 1978" },
	{ "name" : "Sweet Life - I Get Lifted 1983" },
	{ "name" : "Sweet Pea Atkinson - Dance Or Die 1982" },
	{ "name" : "Sweet Thunder - Everybody's Singin' Love Songs 1978" },
	{ "name" : "Sylvester - Body Strong 1979" },
	{ "name" : "Sylvester - Dance (Disco Heat) 1978" },
	{ "name" : "Sylvester - Do Ya Wanna Funk 1982" },
	{ "name" : "Sylvester - Don't Stop (12&quot;) 1983" },
	{ "name" : "Sylvester - Give It Up 1981" },
	{ "name" : "Sylvester - I Need Somebody To Love Tonight 1979" },
	{ "name" : "Sylvester - I Need You 1980" },
	{ "name" : "Sylvester - Menergy 1983" },
	{ "name" : "Sylvester - Stars 1979" },
	{ "name" : "Sylvester - Too Late (12&quot; Mix) 1984" },
	{ "name" : "Sylvester - Trouble In Paradise (12&quot;) 1983" },
	{ "name" : "Sylvia Striplin - Give Me Your Love 1980 --> Uno Melodic rds" },
	{ "name" : "Syreeta - Can't Shake Your Love (Levan Remix) 1981" },
	{ "name" : "System - You Are In My System 1983" },
	{ "name" : "T Connection - At Midnight 1979" },
	{ "name" : "T.C. Curtis - Body Shake (Instr. 12&quot; Version) 1982" },
	{ "name" : "T.C. Curtis - You Should Have Known Better (12&quot;) 1985" },
	{ "name" : "T.S. Monk - Can't Keep My Hands To Myself 1981" },
	{ "name" : "T.S. Monk - Candidate For Love 1981" },
	{ "name" : "Taana Gardner - Heartbeat (12&quot; Levan Mix) 1981" },
	{ "name" : "Taana Gardner - No Frills 1981" },
	{ "name" : "Taana Gardner - When You Touch Me (Levan Mix) 1979" },
	{ "name" : "Taana Gardner - Work That Body (Levan Remix) 1980" },
	{ "name" : "Talking Heads - Burning Down The House 1983" },
	{ "name" : "Talking Heads - Slippery People (12&quot;) 1983" },
	{ "name" : "Talking Heads - Swamp 1983" },
	{ "name" : "Talking Heads - Take Me To The River 1978" },
	{ "name" : "Talking Heads - This Must Be The Place 1983" },
	{ "name" : "Tamiko Jones - Can't Live Without Your Love 1979" },
	{ "name" : "Tammy Lucas - Hey Boy (12&quot;) 1986" },
	{ "name" : "Tasha Thomas - Shoot Me (With Your Love) 1978" },
	{ "name" : "Tata Vega - Get It Up For Love 1978" },
	{ "name" : "Tata Vega - I Just Keep Thinking About You Baby (Ext. 12&quot; Mix) 1979" },
	{ "name" : "Tavares - Don't Take Away The Music 1976" },
	{ "name" : "Teddy Pendergrass - The More I Get, The More I Want 1977" },
	{ "name" : "Teddy Pendergrass - You Can't Hide From Yourself 1977" },
	{ "name" : "Temper - No Favors 1984" },
	{ "name" : "Tempest Trio - Love Machine 1979" },
	{ "name" : "Tenderness - Gotta Keep Trying 1978" },
	{ "name" : "Tenita Jordan - I Don't Wanna Think About It (12&quot;/LP) 1985" },
	{ "name" : "Teri DeSario - Ain't Nothin' Gonna Keep Me From You 1978" },
	{ "name" : "Terri Gonzalez - Treat Yourself To My Lofe 1982" },
	{ "name" : "Terri Wells - I'm Givin' All My Love (12&quot; or LP) 1984" },
	{ "name" : "The Affair - Please Don't Break My Heart (12&quot;) 1985" },
	{ "name" : "The Cut - Kindness For Weakness (12&quot; Levan Mix) 1986" },
	{ "name" : "The Family - Screams Of Passion (12&quot;/LP) 1985" },
	{ "name" : "The It - Donnie (12&quot;) 1986" },
	{ "name" : "The Limit - Say Yeah 1984" },
	{ "name" : "The Police - Voices Inside My Head 1980" },
	{ "name" : "The Quick - Rhythm Of The Jungle 1982" },
	{ "name" : "The Quick - Zulu 1981" },
	{ "name" : "The Who - Eminence Front 1982" },
	{ "name" : "Thelma Houston - Don't Leave Me This Way 1976" },
	{ "name" : "Thelma Houston - I'd Rather Spend The Bad Times With You 1984" },
	{ "name" : "Thelma Houston - I'm Here Again 1977" },
	{ "name" : "Thelma Houston - If You Feel It (12&quot; Remix) 1981" },
	{ "name" : "Thelma Houston - Just Like All The Rest (Dub 12&quot; Vers.) 1983" },
	{ "name" : "Thelma Houston - Saturday Night, Sunday Morning 1979" },
	{ "name" : "Thelma Houston - You Used To Hold Me So Tight (12&quot;) 19 84" },
	{ "name" : "Theo Vaness - I Can't Dance Without You 1979" },
	{ "name" : "Theo Vaness - Nobody But You 1978" },
	{ "name" : "Theo Vaness - Sentimentally It's You 1979" },
	{ "name" : "Third World - Dancing On The Floor 1981" },
	{ "name" : "Third World - Lagos Jump 1983" },
	{ "name" : "Third World - Now That We Found Love 1978" },
	{ "name" : "Third World - One To One (12&quot;) 1985" },
	{ "name" : "Thomas Dolby - Dessidents: The Search For Truth 1984" },
	{ "name" : "Thompson Twins - In The Name Of Love 1982" },
	{ "name" : "THP Orchestra - Good To Me 1979" },
	{ "name" : "THP Orchestra - Two Hot For Love 1978" },
	{ "name" : "THP Orchestra - Who Do You Love 1979" },
	{ "name" : "Three Million - I've Been Robbed (12&quot;) 1983" },
	{ "name" : "Three Ounces Of Love - Star Love 1978" },
	{ "name" : "Timmy Thomas - Stone To The Bone 1977" },
	{ "name" : "Tin Tin - Kiss Me 1982" },
	{ "name" : "Tina B. - Honey To A Bee (12&quot; Mix) 1984" },
	{ "name" : "Tina Turner - Afterglow (12&quot; Promo) 1986" },
	{ "name" : "Tom Browne - Crusing 1983" },
	{ "name" : "Tom Tom Club - Le Elephant 1981" },
	{ "name" : "Tom Tom Club - Pleasure Of Love 1983" },
	{ "name" : "Tom Tom Club - Wordy Rappinghood 1981" },
	{ "name" : "Tomorrow's Edition - You Turn Me On 1982" },
	{ "name" : "Toney Lee - Reach Up 1982" },
	{ "name" : "Tony Cook & The Party People - On The Floor 1984" },
	{ "name" : "Tony McKenzie - Ha-Chica 1983" },
	{ "name" : "Tony Orlando - Don't Let Go 1978" },
	{ "name" : "Tony Paris - Electric Automan (Levan 12&quot; Remix) 1985" },
	{ "name" : "Total Contrast - Takes A Little Time (12&quot;/LP) 1985" },
	{ "name" : "Total Contrast - The River (12&quot;) 1985" },
	{ "name" : "Touch - Love Fixation (12&quot;) 1987" },
	{ "name" : "Touch - Without You (12&quot;) 1986" },
	{ "name" : "Touchdown - Ease Your Mind 1982" },
	{ "name" : "Tracy Weber - Sure Shot (2 different 12&quot;s; one has a Instr. Version that 1982" },
	{ "name" : "Tracy Weber - Sure Shot (Instr. Version released as B Side of One Step At A Time) 1983" },
	{ "name" : "Tramaine - Child Of The King (12&quot;) 1986" },
	{ "name" : "Tramaine - Fall Down Spirit Of Love (12&quot;) 1985" },
	{ "name" : "Tramaine - The Rock (Levan 12&quot; Remix) 1987" },
	{ "name" : "Trammps - Body Contact Contract 1977" },
	{ "name" : "Trammps - Can We Come Together 1976" },
	{ "name" : "Trammps - Disco Party 1977" },
	{ "name" : "Trammps - Love Insurance Policy 1979" },
	{ "name" : "Trammps - People Of The World 1977" },
	{ "name" : "Trammps - Stop And Think (Remix LP) 1977" },
	{ "name" : "Trammps - Wha Happened To The Music 1983" },
	{ "name" : "Troiano - We All Need Love 1979" },
	{ "name" : "Trussel - Love Injection 1980" },
	{ "name" : "Twennynine - Fancy Dancer 1981" },
	{ "name" : "Two Tons - Do You Wanna Boogie, Hunh? 1980" },
	{ "name" : "Two Tons - Earth Can Be Just Like Heaven 1980" },
	{ "name" : "Two Tons - I Got The Feeling 1980" },
	{ "name" : "Ullanda McCullough - Bad Company 1981" },
	{ "name" : "Undisputed Truth - You + Me = Love 1976" },
	{ "name" : "Unique - What I Got Is What You Need 1983" },
	{ "name" : "Universal Robot Band - Dance & Shake Your Tambourine 1977" },
	{ "name" : "Unlimited Touch - Searching To Find The One 1981" },
	{ "name" : "Upfront - Infatuation 1983" },
	{ "name" : "Valerie Oliver - Get The Money 1983" },
	{ "name" : "Van McCoy - Party 1976" },
	{ "name" : "Van McCoy - Rhythms Of The World 1976" },
	{ "name" : "Vanilla Mix - Easier Said Than Done (12&quot;) 1987" },
	{ "name" : "Vanity - Under The Influence (12&quot;) 1986" },
	{ "name" : "Vesta Williams - Don't Blow A Good Thing (12&quot; Remix) 1987" },
	{ "name" : "Vicky D - This Beat Is Mine 1982" },
	{ "name" : "Vikki Love - Stop Playing On Me (12&quot;) 1985" },
	{ "name" : "Village People - Fire Island 1977" },
	{ "name" : "Village People - San Francisco 1977" },
	{ "name" : "Viola Wills - If You Could Read My Mind 1980" },
	{ "name" : "Visage - Fade To Grey 1980" },
	{ "name" : "Visual - Somehow, Someway 1983" },
	{ "name" : "Visual - The Music Got Me 1983" },
	{ "name" : "Voice In Fashion - Only In The Night (12&quot; Dub Mix) 1987" },
	{ "name" : "Voyage - From East To West 1977" },
	{ "name" : "Voyage - From East To West 1978" },
	{ "name" : "Voyage - I Love You Dancer 1980" },
	{ "name" : "Wally Badarau - Chief Inspector/Novela Das Nove (12&quot;) 1986" },
	{ "name" : "Wally Jump, Jr. - Don't Push Your Luck (LP) 1987" },
	{ "name" : "Wally Jump, Jr. - Private Party (12&quot;) 1987" },
	{ "name" : "Wally Jump, Jr. - Turn Me Loose (12&quot;) 1986" },
	{ "name" : "Wanda - I Must Be Dreamin' 1982" },
	{ "name" : "War - Galaxy 1977" },
	{ "name" : "Wardell Piper - Super Sweet 1979" },
	{ "name" : "Warp 9 - Light Years Away 1983" },
	{ "name" : "Was (Not Was) - Tell Me That I'm Dreaming 1982" },
	{ "name" : "Weather Girls - No One Can Love You More Than Me (12&quot;/LP) 1985" },
	{ "name" : "Webster Lewis - Let Me Be The One 1981" },
	{ "name" : "Weeks & Co. - Go With The Flow 1982" },
	{ "name" : "Weeks & Company - Rock Your World 1981" },
	{ "name" : "Whatnauts - Help Is On The Way 1982" },
	{ "name" : "Whitney Houston - Love Will Save The Day (12&quot; Remix) 1987" },
	{ "name" : "Whitney Houston - Thinking About You (12&quot;) 1985" },
	{ "name" : "Will Powers - Adventures In Success 1983" },
	{ "name" : "Willie Colon - Set Fire To Me (12&quot;) 1986" },
	{ "name" : "Willie Colon - She Don't Know I'm Alive (12&quot;) 1986" },
	{ "name" : "Willie Hutch - In And Out 1982" },
	{ "name" : "Winners - Get Ready For The Future 1978" },
	{ "name" : "Wish - Touch Me (All Night Long) 1984" },
	{ "name" : "World Premiere - Share The Night 1984" },
	{ "name" : "Xena - On The Upside 1983" },
	{ "name" : "Yarbrough & Peoples - Don't Waste Your Time (12&quot; Remix) 1984" },
	{ "name" : "Yaz - Don't Go 1982" },
	{ "name" : "Yazoo - Situation 1982" },
	{ "name" : "Yazoo - State Farm 1983" },
	{ "name" : "Yello - Call It Love (12&quot; Remix) 1987" },
	{ "name" : "Yellow Magic Orchestra - Computer Games 1979" },
	{ "name" : "Yes - Owner Of A Lonely Heart (12&quot;) 1983" },
	{ "name" : "Yoko Ono - Walking On Thin Ice 1981" },
	{ "name" : "Young & Co. - I Like What You're Doing (To Me) 1980" },
	{ "name" : "Young & Company - Such A Feeling (12&quot;) 1986" },
	{ "name" : "Yvonne Gage - Garden Of Eden 1981" },
	{ "name" : "Zena Dejonay - I've Got To Find A Way 1983" },
	{ "name" : "Zulema - Change 1978"}
	]
};